#!/usr/bin/env bash

BINPATH=/usr/bin/OwaViewer

echo "Creating script"
echo "#!/usr/bin/env bash" > $BINPATH
echo "/Applications/OwaViewer.app/Contents/MacOS/OwaViewer \$@" >> $BINPATH

chmod +x $BINPATH


#sudo ln -sf /Applications/OwaViewer.app/Contents/MacOS/OwaViewer /usr/bin/OwaViewer
